version: "3.8"

x-zoo-envs: &zoo-envs
  ZOOKEEPER_CLIENT_PORT: 2181
  ZOOKEEPER_TICK_TIME: 2000
  # ZOOKEEPER_SERVERS: zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888

x-kafka-envs: &kafka-envs
  # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  # KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2181,zoo-3:2181
  # KAFKA_MIN_INSYNC_REPLICAS: 3
  # KAFKA_REPLICA_LAG_TIME_MAX_MS: 30000
  # KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 256000
  # KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
  # KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 10485760

services:
  zoo-1:
    container_name: zoo-1
    hostname: zoo-1
    image: confluentinc/cp-zookeeper
    environment:
      <<: *zoo-envs

  kafka-1:
    user: root
    container_name: kafka-1
    hostname: kafka-1
    image: confluentinc/cp-kafka
    depends_on:
      - zoo-1
    volumes:
      - type: bind
        source: ./kafka-solo/kafka-1/secrets
        target: /etc/kafka/secrets
      - type: bind
        source: ./kafka-solo/client
        target: /tmp/client/
    environment:
      KAFKA_BROKER_ID: 1
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,SSL://kafka-1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: pass.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: pass.txt
      KAFKA_SSL_KEY_CREDENTIALS: pass.txt
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:
      <<: *kafka-envs

  clients:
    container_name: "clients"
    build: ./clients
    volumes:
      - type: bind
        source: "./clients"
        target: "/code"
    tty: true
    stdin_open: true
  

volumes:
  zoo-1-data:
  kafka-1-data: