execTime: 60
recordMessage: true

pubConf:
  number: 1
  server: "nats://nats-1"
  stream: "STREAM"
  subject: "STREAM.pull"
  # messageRate: "1kB"
  messageSize: "100kB"
  # messageSize: "1kB"

subConf:
  number: 1
  server: "nats://nats-1"
  stream: "STREAM"
  subject: "STREAM.pull"
  durable: "pull-consumer"
  mode: pull
  batchSize: 1
  maxWait: 50