execTime: 60
recordMessage: true

pubConf:
  number: 1
  server: "nats://nats-1"
  stream: "STREAM"
  subject: "STREAM.push"
  # messageRate: "1kB"
  # messageSize: "100kb"
  messageSize: "1kb"

subConf:
  number: 1
  recordMessage: true
  server: "nats://nats-1"
  stream: "STREAM"
  subject: "STREAM.push"
  durable: "push-consumer"
  queueGroup: "push-consumer-queue"
  mode: push
  maxWait: 50