
execTime: 10

pubConf:
  server: "nats://nats-1"
  stream: "STREAM"
  subject: "STREAM.pull"
  # messageRate: "1kB"
  messageSize: "1kB"
  number: 1

subConf:
  number: 1
  recordMessage: true
  server: "nats://nats-1"
  stream: "STREAM"
  subject: "STREAM.pull"
  durable: "pull-consumer"
  mode: pull
  batchSize: 1
  maxWait: 50
