
execTime: 30
publisherRiseTime: 5
subscriberFallTime: 5

pubConf:
  server: "nats://nats-1"
  subject: "test-subject"
  # messageRate: "1kB"
  messageSize: "1kB"
  number: 1

subConf:
  number: 2
  recordMessage: true
  server: "nats://nats-1"
  subject: "test-subject"
  maxWait: 50
  queueGroup: "queue-group"
